### ISSUE TITLE
PESI: synonym type

### ISSUE THREAD

**Issue by Alectoria** [ropensci/taxizesoap#10]
Euro+Med is really neat in that it gives information on the type of synonym (e.g. misapplied, homotypic synonym). As far as I know, this is the only plant taxonomic database to offer this information. However, I can't retriete the data when using taxizesoap (v 0.1.0.99). Same goes for taxize::eubon. 

In the example below, I get status == "synonym" but the webinterface tells me it's a **homotypic synonym** of "Ochlopoa annua" (http://ww2.bgbm.org/EuroPlusMed/PTaxonDetail.asp?NameId=7711786&PTRefFk=7100000)

```
test2 <- pesi_search("Poa annua")

test2
  input   GUID   url scientificname   authority    rank  status
  1 Poa annua 81675361-4CA2-4A87-A588-3941DF738A4F http://www.eu-nomen.eu/portal 
  /taxon.php?GUID=81675361-4CA2-4A87-A588-3941DF738A4F      Poa annua    L. Species synonym
 valid_guid     valid_name valid_authority kingdom phylum class order family genus
 1 93A25572-521E-4130-B8C5-9C7D332E5605 Ochlopoa annua  (L.) H. Scholz    <NA>   <NA>  <NA>  
  <NA>   <NA>  <NA>
 citation
  1 ValdÈs, B. & Scholz, H.; with contributions from Raab-Straube, E. von & Parolly, G. (2009):  
Poaceae (pro parte majore). Euro+Med Plantbase - the information resource for Euro-Mediterranean 
plant  diversity. Poa annua L.. Accessed through: Euro+Med PlantBase at http://ww2.bgbm.org
/euroPlusMed/PTaxonDetail.asp?UUID=81675361-4CA2-4A87-A588-3941DF738A4F
match_type
1      exact
```

It's probably an issue on the PESI side but I just wanted to check with you, first.

**Comment by sckott** [comment]
Thanks! I'll take a look soon, at a conf. right now

**Comment by sckott** [comment]
Sorry for the delay. 

That other synonym information is not available in that fxn, i'll check other ones

**Comment by sckott** [comment]
I don't see synonym info anywhere in the PESI web services or in eubon. Sorry about that. Thoughts?

**Comment by Alectoria** [comment]
It's really strange that there is a mismatch between Euro+Med and PESI/eubon. The Euro+Med database definitely stores this information (I have it in file format). I will get in touch with their people.

Thanks for looking into this, @sckott!

**Comment by sckott** [comment]
Thanks for getting in touch with them!

**Comment by Alectoria** [comment]
I was able to get a hold of somebody at EU BON and they forwarded my request to the developers. Will keep you posted, @sckott.

**Comment by sckott** [comment]
thanks!
