### ISSUE TITLE
worms_children() encounters error when one of the AphiaIDs has no children

### ISSUE THREAD

**Issue by willgearty** [ropensci/taxizesoap#12]
When using `worms_children()`, if a vector of AphiaIDs is provided, but one or more of the AphiaIDs has no children, the function encounters the following error:
`Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match`
I imagine this is due to the function trying to `rbind` the normal children results (which have 26 columns, in my experience) and the "noresults" results (which have two columns).

By the way, very excited that this package is working again! Thanks for all your support, Scott!

**Comment by sckott** [comment]
Thanks for the issue - Can you give example of id that doesn't have children

**Comment by willgearty** [comment]
833826 has no children.
`worms_children(ids=c(156484,833826))` should replicate the problem.

**Comment by sckott** [comment]
Thanks!

Actually, to be consistent with `taxize`, we shouldn't be rbinding results together from different taxa. Agreed?

**Comment by willgearty** [comment]
I quite like the rbinded the results, but I suppose consistency with `taxize` would be good.

**Comment by sckott** [comment]
I think consistency is important to have. I'll include in the examples how to rbind results together.

**Comment by sckott** [comment]
@willgearty try again after reinstalling, let me know

**Comment by willgearty** [comment]
Yep, seems to work great now. Thanks!

**Comment by sckott** [comment]
great 👍
