### ISSUE TITLE
Graceful fail condition for get_wormsid and others

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/taxizesoap#14]
When feeding a name not in the db into `get_wormsid()` (and I'm guessing others), a no match causes the entire function to crash.  e.g.

```
> get_wormsid(searchterm = c("Agarum clathratum", "bad species name"))

Retrieving data for taxon 'Agarum clathratum'

Retrieving data for taxon 'bad species name'

Error in `[.data.frame`(worms_df, , c("AphiaID", "scientificname", "status",  : 
  undefined columns selected
```

Can this fail gracefully and just return an NA?

**Comment by sckott** [comment]
changes in 9b05df113084a8c165a2b707c36eb8e20705114e 

reinstall - let me know if it works, it should

**Comment by jebyrnes** [comment]
Bueno!
