### ISSUE TITLE
Error: get_wormsid produces missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by miriamgrace** [ropensci/taxizesoap#19]
Hi, I'm not sure if this is the right place to post errors, so sorry if not. I'm running a query to get WoRMS ID corrsponding to scientific names of various species in OBIS, but I get the following error for some species:

`Error in if (els[1] != "SOAP" && els[1] != "SOAP-ENV") code <- NULL else code <- els[2] : missing value where TRUE/FALSE needed`

The basic query is:
`ukeez_aphia <- get_wormsid(searchterm = ukeez_names, accepted = TRUE,ask=FALSE, verbose=FALSE)`

I can add more code if needed. Thanks for any suggestions!

**Comment by sckott** [comment]
hi @miriamgrace thanks for your question! 

Did you know that WoRMS is now in the regular `taxize` package?  Install taxize `install.packages("taxize")` and see functions starting with `worms` 

i just updated the README here to note the change
