### ISSUE TITLE
‘SSOAP’ is not available (for R version 3.6.2)

### ISSUE THREAD

**Issue by Moose37** [ropensci/taxizesoap#20]
Any advice?

**Comment by sckott** [comment]
hi @Moose37 thanks for the ping. taxizesoap is not really maintained anymore. what data source are you trying to use?

**Comment by Moose37** [comment]
Hi. I've been using it to get full WoRMS aphia records for a species list.

**Comment by sckott** [comment]
@Moose37 there's a separate package for WORMS https://github.com/ropensci/worrms and WORMS data is available in the taxize package as well https://github.com/ropensci/taxize - do either of those work for what you need?

**Comment by Moose37** [comment]
They do. I was just confirming that taxizesoap was out before over hauling my code. Thanks for the quick responses. appreciate it.
