### ISSUE TITLE
XMLSchema broken for R versions >= 3.2 

### ISSUE THREAD

**Issue by sckott** [ropensci/taxizesoap#4]

**Comment by MRittinghouse** [comment]
Do you feel it would be productive to write to OmegaHat to develop a separate version of XMLSchema with a more limited scope of functionality to return to CRAN? 

Their reasoning for removing the package was that the code from this was taken out of the SSOAP package so that it could be used on arbitrary XML schema and not just those contained within WSDL files.

**Comment by sckott** [comment]
Perhaps, though I've not had much luck getting any responses from Duncan (the person behind OmegaHat). That's why I have a forked version under my github account https://github.com/sckott/XMLSchema 

With drat (https://github.com/eddelbuettel/drat) we don't even need a version on CRAN, but a fixed version in a github repo, then we can just use that...just need to get it fixed first, but haven't been able to track down the problem.

**Comment by MRittinghouse** [comment]
My issues are fairly specific, and there may be better solutions with R. Part of my problem may just be that I don't fully understand why the XMLSchema package was removed from CRAN. 

I'm hoping to incorporate the AphiaID lookup as a module for processing incoming spreadsheets between multiple users. I was hoping to be able to give the modules to less-experienced R users as a standalone product with the dependencies already mapped into my scripts, and directing the users to download external packages may complicate the process. 

Thank you for the amazing work in this repository, by the way!

**Comment by sckott** [comment]
I have been playing with a Javascript library that can turn SOAP web services into REST based ones - which would allow us to serve WORMS data directly into the taxize package  - but that's not quite working yet.

**Comment by MRittinghouse** [comment]
My programming experience is fairly limited, but I will keep my eyes open for any solutions or workarounds, and be sure to let you know if I spot anything interesting.

**Comment by sckott** [comment]
cool, thanks

**Comment by vinsondoyle** [comment]
Is there any progress on this issue? If not, can I revert to an older version of R to run taxizesoap? Which version?

Also, my interest in taxizesoap is the ability to query mycobank and/or index fungorum. Please consider adding indexfungorum. Unfortunately, it also uses XML and SOAP (http://www.programmableweb.com/api/index-fungorum-fungus).

Thanks

**Comment by sckott** [comment]
No, no progress.  I think I tracked down where the problem is, sort of, but the change was in base R distribution, and there's no way in a million years I'd get a fix in to base R (maybe if I was more important in the R world).  

You need an R version less than R 3.2, eg,. R 3.1.2

**Comment by sckott** [comment]
Also check out ropensci/taxize#466 - there's a new EU sponsored API that will expose PESI and WORMS in REST (non-SOAP), so we should have it in `taxize` hopefully soon.

**Comment by sckott** [comment]
Regarding fungorum: I think it's available via PESI -e.g., http://www.eu-nomen.eu/portal/taxon.php?GUID=urn:lsid:indexfungorum.org:names:17703  Didn't test with this package, but should work.  I don't know the extent to which fungorum is in PESI

looks like they may have a REST interface, e.g, http://www.indexfungorum.org/ixfwebservice/fungus.asmx/NameSearch?SearchText=Gymnopus&AnywhereInText=true&MaxNumber=2

**Comment by vinsondoyle** [comment]
Thanks for the update! I will keep an eye on the PESI integration and, in the interim, use an older version of R.

**Comment by sckott** [comment]
@vinsondoyle @MRittinghouse see https://github.com/ropensci/taxize/issues/471#issuecomment-149753755

**Comment by mpnelsen** [comment]
@sckott (19 Oct 2015) "I think I tracked down where the problem is, sort of, but the change was in base R distribution"

Is there any chance it was corrected in R 3.3?  Thanks.

**Comment by sckott** [comment]
@MRittinghouse 

I got a email notification that you said 

> Is there any chance it was corrected in R 3.3? Thanks.

I don't know. I can look.

**Comment by mpnelsen** [comment]
Actually, I'd posted it, but realized 3.3 isn't officially released yet (and deleted my post).

**Comment by sckott** [comment]
good question though, will check before it's released at least

**Comment by mpnelsen** [comment]
Thanks!  The best option for accessing MycoBank is still to use R 3.1, right?

**Comment by sckott** [comment]
yes, via 3.1

**Comment by sckott** [comment]
@mpnelsen nope, doesn't work in 3.3, we're stuck with < 3.2 still

**Comment by mpnelsen** [comment]
Thanks!

**Comment by tomjwebb** [comment]
@sckott Hey Scott, any progress on this, either here or via the PESI route? Or is it still back to <3.2 if I want to get anything out of WoRMS? Thanks!

**Comment by sckott** [comment]
hey @tomjwebb i'll check again, maybe it's been fixed...

**Comment by sckott** [comment]
Okay, reinstall from github: `devtools::install_github("ropensci/taxizesoap")`  - Seems to be working now with `XMLSchema` from omegahat on github, and the version of `SSOAP` I froze on my github acct. Both of those are on our drat now as well. The  `install_github("ropensci/taxizesoap")` should install those two for you automatically. Updated instructions here https://github.com/ropensci/taxizesoap#install-taxizesoap

**Comment by sckott** [comment]
^^ @tomjwebb

**Comment by tomjwebb** [comment]
@sckott Fantastic, thanks Scott - I'll give it a go later on and let you know if I hit any problems. Thanks again!
