### ISSUE TITLE
pesi_ functions for Euro+Med

### ISSUE THREAD

**Issue by Alectoria** [ropensci/taxizesoap#8]
I noticed that pesi_ functions return en empty result when supplied taxon names have spelling mistakes. For example, take the name "Pinus sylvvestris" (correctly spelt "Pinus sylvestris"):

```
> pesi_search("Pinus sylvvestris")
NULL

> pesi_guid("Pinus sylvvestris")
""
```

However, when I enter the name in the online version (http://ww2.bgbm.org/EuroPlusMed/query.asp), I am referred to the page with the correct name. So, the online version has a spell checker but pesi_ functions are excluded from it. Any particular reason for that?

I've used R version: 3.1.0 and  taxizesoap: 0.1.0.99 for the query.

**Comment by sckott** [comment]
Thanks for the report!  My guess is that they could very well have a spell checker for their web application that does not get used in the web service we use here, but I'll check...

**Comment by sckott** [comment]
If you look at the `matchTaxon` and `matchTaxa` methods here http://www.eu-nomen.eu/portal/soap.php# - they say they do fuzzy matching, but apparently not very well, or not at all maybe. If you have names that may be mis-spelled, you may want to use something like `gnr_resolve()` in the `taxize` pkg first

**Comment by Alectoria** [comment]
@sckott Thanks for looking into this!

**Comment by sckott** [comment]
@Alectoria I don't think there's anything I can do here, okay if I close?

**Comment by Alectoria** [comment]
@sckott  sure, go ahead

**Comment by sckott** [comment]
Sorry I can't help more!
