### ISSUE TITLE
Fuzzy matching results from PESI

### ISSUE THREAD

**Issue by Alectoria** [ropensci/taxizesoap#9]
I am using Euro+Med quite a bit for my work and am very happy for PESI-support in taxizesoap (and now in taxize via eubon). I have noticed, however, that it does not support fuzzy matching, although PESI should implement it: http://www.eu-nomen.eu/portal/soap.php# (see matchTaxon, matchTaxa).

For example, take the taxon name "Poa annuaa" (correct spelling: "Poa annua"). When using the webinterface of Euro+Med (http://ww2.bgbm.org/EuroPlusMed/query.asp), you get directed to the correct spelling version, and then the accepted name. However, in taxizesoap (v. 0.1.0.99), names are only matched exactly, w/o fuzzy matching:

```
test <-  pesi_search("Poa annuaa")
test
NULL
```

Thanks!

**Comment by sckott** [comment]
Thanks! I'll take a look soon, at a conf. right now

**Comment by sckott** [comment]
I sort of remember this from before, but we should includee in the docs for the pkg. The matching tool must be differnet or used differently on the website vs. in the PESI web services. 

I don't think EUBOn would help in this case either as they do have `scientificNameLike` option, but it's for giving a partial name, the beginning part of the name, not necessarily a full name, with some letters incorrect. 

I wish we could do better! It seems that one needs to use a resolver service first (like gnr_resolve or iplant_resolve in taxize), then go to PESI/EUBON to find matches in their database.

**Comment by Alectoria** [comment]
Ha, so it is on the PESI/eubon side. I will contact their developers and ask if they could implement fuzzy matching in the future. Would be really neat. 

Meanwhile, I think it's a good idea to include some info in the docs that fuzzy matching is not supported.

Thanks for looking into this!

**Comment by sckott** [comment]
Thanks for contacting them.  We'll include some notes about fuzzy matching in the docs
